apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - loki-helmchart.yaml
  - prometheus-helmchart.yaml
  - promtail-helmchart.yaml
  - grafana-helmchart.yaml
