finguide-api:
  replicaCount: 1
  image:
    repository: ghcr.io/svoronkov-les13/finguide-api
    tag: latest

finguide-web:
  replicaCount: 1
  image:
    repository: ghcr.io/svoronkov-les13/finguide-web
    tag: latest
