apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: finguide-demo
resources:
  - ../../base
nameSuffix: -demo
images:
  - name: ghcr.io/svoronkov-les13/finguide-api
    newTag: demo
  - name: ghcr.io/svoronkov-les13/finguide-web
    newTag: demo
patches:
  - target:
      kind: Namespace
      name: finguide
    patch: |-
      - op: replace
        path: /metadata/name
        value: finguide-demo
  - target:
      kind: Deployment
      name: finguide-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: finguide-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
