apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: finguide
resources:
  - ../../base
  - ../../base/keycloak
  - configmap.yaml
  - ingress.yaml
  - keycloak-realm.yaml
images:
  - name: ghcr.io/svoronkov-les13/finguide-api
    newTag: les13
  - name: ghcr.io/svoronkov-les13/finguide-web
    newTag: les13
