apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - finguide-api/deployment.yaml
  - finguide-api/pvc.yaml
  - finguide-api/service.yaml
  - finguide-web/deployment.yaml
  - finguide-web/service.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: finguide
    includeSelectors: true
