apiVersion: v1
kind: ConfigMap
metadata:
  name: finguide-api-config
data:
  FINGUIDE_DEMO_MODE: "true"
  FINGUIDE_DATASOURCE_URL: "jdbc:h2:file:/data/finguide-dev;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1"
  FINGUIDE_DATASOURCE_USERNAME: "sa"
  FINGUIDE_H2_CONSOLE_ENABLED: "false"
  KEYCLOAK_ISSUER_URI: "https://finguide-dev.les13.tech/auth/realms/finguide-dev"
  KEYCLOAK_AUDIENCE: "finguide-api"
  FINGUIDE_SWAGGER_CONFIG_URL: "/finguide-api/v3/api-docs/swagger-config"
  FINGUIDE_SWAGGER_API_DOCS_URL: "/finguide-api/v3/api-docs"
