apiVersion: v1
kind: ConfigMap
metadata:
  name: finguide-api-config
data:
  FINGUIDE_DEMO_MODE: "true"
  FINGUIDE_DATASOURCE_URL: "jdbc:postgresql://finguide-api-postgres-dev:5432/finguide"
  FINGUIDE_DATASOURCE_USERNAME: "finguide"
  FINGUIDE_H2_CONSOLE_ENABLED: "false"
  KEYCLOAK_ISSUER_URI: "https://finguide-dev.les13.tech/auth/realms/finguide-dev"
  KEYCLOAK_AUDIENCE: "finguide-api"
  FINGUIDE_SWAGGER_CONFIG_URL: "/finguide-api/v3/api-docs/swagger-config"
  FINGUIDE_SWAGGER_API_DOCS_URL: "/finguide-api/v3/api-docs"
